---
config:
  layout: dagre
  look: classic
  theme: neutral
---
flowchart TD
    A["Bien"] --> B["Phusis"] & C["Pneuma"] & E["Referencias"] & F["Segundo Grado"]
    B --> B1["Conceptos"] & B2["Tipos Bien Natural"]
    B1 --> B11["Movimiento"] & B12["Telos"] & B13["Ergon"] & B14["Origen"] & B15["Being Good"] & B16["Max Bien"]
    B2 --> B21["Externos"] & B22["Body"] & B23["Psuche"] & B24["Politike"]
    C --> C1["Ciencia"] & C2["Conceptos"]
    C1 --> C11["Comparación"] & C12["Ciencias"]
    C2 --> C21["Energeia"] & C22["Logos"] & C23["Ontología"] & C24["Causa"]
    B23 --> D1["Pasiones"] & D2["Carácter"] & D3["Acción"] & D4["Hexeis"] & D5["Partes del alma"]
    B13 -->  B131["TH"] & B132["E. Argument"]
